# Copyright 2023 Abisko LLC
version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
